DROP DATABASE IF EXISTS Oouch;
CREATE DATABASE IF NOT EXISTS Oouch;
GRANT ALL PRIVILEGES ON Oouch.* TO 'qtc'@'%' IDENTIFIED BY 'clarabibi2019!';
GRANT ALL PRIVILEGES ON Oouch.* TO 'qtc'@'localhost' IDENTIFIED BY 'clarabibi2019!';
use Oouch;

CREATE TABLE user (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(120),
  email VARCHAR(120),
  password_hash VARCHAR(128)
);
