# Generated by Django 2.2.4 on 2021-12-15 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_server', models.CharField(max_length=100)),
                ('ssh_user', models.CharField(max_length=100)),
                ('ssh_key', models.CharField(max_length=3000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunSQL(
            sql='insert into auth_user (password, username, email) values (\'pbkdf2_sha256$150000$PotzkUUOTeGh$nrli7GF5JlQfmEwoe7JTTh76NdLlpXVQRxTJTFEfpYw=\', \'gulu\', \'gulu@oouch.htb\')'    
        ),
    ]
